### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#307] opened 2015-09-18 11:45 UTC
This issue is created to collect thoughts about Java 8 support on OASP.

**Comment by sobkowiak** [comment] 2015-09-18 11:49
As discussed with @hohwille we should not use the  J8 features (like lambdas) at the beginning, because we still want support J7. But we should try to design the features to be easy usable in Java 8 (e.g. rearrange the callback interfaces to be easy usable in J8 lambdas).

**Comment by hohwille** [comment] 2015-10-30 21:51
Designing interfaces as functional interface is pretty simple.
The main thing is that java did not offer common interfaces for regular callbacks like Provider, Consumer, Predicate/Filter, Function, etc. 
These have all been added in J8. So we can only define custom callback interfaces or use the most general ones such as Runnable and Callable.
IMHO there is not much more about it.
Using J8 in a project is nice progress compared to before. Lambdas and streams are cool as well as JSR310 (tough I already had my dark hours with it - see https://github.com/ThreeTen/threeten/issues/353).
In my current project I am using J8 on OASP and there is nothing out of OASP that I am missing or that could be improved to better support J8.
The problem is really that things move so slow. There are people out there that want to use OASP with J6 and that is not possible. I never thought that J6 is still relevant for new projects and production use today but JEE app server world seems to be the ultimate "tanker boat slow you down" thing...
After being productive on spring-boot I can not believe anymore why someone would really start a new project with a full blown JEE app server.

**Comment by amarinso** [comment] 2015-10-30 22:50
Speaking of moving slow... just 4 days ago (Oct 26) Oracle released Weblogic Server 12.2.1 with  full support for Java 8 and Java EE 7 (release date June 12, 2013). 

I think that clients relying on Java EE don't care too much about developer productivity, besides they suffer from "Nobody ever got fired for choosing IBM" syndrome.

One of the reasons they provide is that operations is easier with an integrated solution like Oracle Enterprise Manager for controlling the whole application landscape. Doing similar task with Tomcat or micro services is more involved and has no clear support from vendors.

And then there is the marketing side of it, we can not compete with "vendor X" commercials with technical reasons...

On Javascript-land there is at least a new breed of "transpilers" that allow us to program with newer features of the language and run them in older implementations (babel, traceur, ...) 

Please @hohwille elaborate on the things you found more interesting and most used in J8 on your project for when we have the opportunity to move on.

**Comment by hohwille** [comment] 2015-11-17 08:13
@amarinso thanks for your feedback.
For Javascript we are in the progress of moving to typescript that itself is based on ES6 and the compiler does transpiling to plain old JS.
Still we moved away from GWT exactly for such reason. However transpiling Java to JS is really a different story.

For all the enterprise and support stuff people can go with Capgemini and use OASP in combination with Devon on the long run.

**Comment by hohwille** [comment] 2016-07-18 13:57
So could we sum up that we just close this issue as "invalid". I see no actual API or thing to change so that we could better support java8 currently. So IMHO this is just an open issue with no progress.

**Comment by hohwille** [comment] 2018-01-15 10:31
As no further feedback was given I close this issue. To conclude:
* we do support Java8
* we will introduce new modules using Java8 features and requiring Java8 in the future
* we will however keep Java7 compatibility for the platform and fundamentals for still a long time as we do not want to break any existing project and guarantee reliability of our solution.

**Closed by hohwille** 2018-01-15 10:31 UTC
Labels: invalid
