### ISSUE TITLE
Insufficient OrderPosition -> Staff relations

### ISSUE THREAD

**Issue by maybeec** [oasp/oasp4j#341] opened 2015-11-04 08:30 UTC
Currently, an OrderPosition is linked to an Offer, which can represent either a single drink, meal, side dish, or any combination of these. 
The problem is now, that we have to assign the cook or barkeeper to the OrderPosition and thus to an Offer. So for providing meals to the restaurant clients, like a coke combined with frites for a single price, it is not possible to let the barkeeper make the drink and the cook make the meal. The issue persist if the cook or barkeeper want to set the drink or the meal to the state 'prepared'. This state is global for the offer and thus cannot be tracked independently for the drinks/meals/side dishs.

**Comment by hohwille** [comment] 2015-11-04 14:50
IMHO this is more or less a duplicate of #101.
The cook is assigned to OrderPosition via property cookId.
The waiter is assigned to OrderPostion via Order and via Table.

That is IMHO sufficient. In many restaurants the waiter is also perparing and serving the drinks. It is currently unspecified if the barkeeper would prepare the drink instead and the waiter would only serve it. However doing an assignment and state-management here might be overkill. Did you ever work as a waiter? UX team is also in charge to interview a real waiter. I think that we overengineer problems as IT guys.

**Comment by may-bee** [comment] 2015-11-04 14:56
> In many restaurants the waiter is also perparing and serving the drinks.

It depends :) if you have a look at larger restaurants, which are also a bar or a brewery, you will easily see barkeepers. For smaller ones, I agree with you.
Nevertheless, it has been experienced by the students as there is a role barkeeper. We should potentially then remove this role to not confuse people.

I think in general, this issue can be reduced to the lack of specification. These are just observations, which lead to confusions in practice.

**Comment by hohwille** [comment] 2015-11-17 06:55
That part is actually specified. Maybe you never read the spec.

**Comment by may-bee** [comment] 2015-11-17 08:07
Meanwhile there is a specification for the restaurant?
Never heard about that. @MarcoRose tried to setup one, but did not get results which have been proven to be good enough. That is my latest state.

**Comment by hohwille** [comment] 2018-01-15 10:21
All replaced with MTS. If you still see issues, raise a new ticket there.

**Closed by hohwille** 2018-01-15 10:21 UTC
