### ISSUE TITLE
JAX-RS @Path URI matching bug

### ISSUE THREAD

**Issue by jhcore** [oasp/oasp4j#490] opened 2016-09-14 10:10 UTC
I got an **important** error in the new version of Devonfw. I have confirmed this bug with the downloading the last version of Devonfw and creating a new server and extjs client (just to confirm it).

I created a new client and server with the actual version and created with CobiGen a simple CRUD of a class called PPBEntity. CobiGen by default create the methods getPPB(String), savePPB(PPBEto), deletePPB(String), findPPBsByPost(PPBSearchCriteriaTo). Then I created a simple grid with a store that has a proxy with the service search (backoffice-server/services/rest/ppbmanagement/v1/ppb/search) and I got the next bug in the server:

[M: javax.ws.rs.BadRequestException: id is not a number

This happen because the server matching the URL with the next service GET:
```java
@GET
  @Path("/ppb/{id}/")
  public ResponseEntity<PPBEto> getPPB(@PathParam("id") String id) {
    (...)
  }
```
Instead of this POST method
```java
@Path("/ppb/search")
  @POST
  public PaginatedListTo<PPBEto> findPPBsByPost(PPBSearchCriteriaTo searchCriteriaTo) {

    return this.ppbmanagement.findPPBEtos(searchCriteriaTo);
  }
```
As you can see the server interpret "search" as id and this is the reason because of we get this error.

I have the example projects if it is necessary

**Comment by amarinso** [comment] 2016-09-14 13:28
I've checked and it is not a bug on the server side but an issue on the client. 

I will open an issue on the other repository and close this one.

**Closed by amarinso** 2016-09-14 13:28 UTC
Labels: bug
