### ISSUE TITLE
Login with cook id fails with Whitable Error Page 

### ISSUE THREAD

**Issue by ssarmokadam** [oasp/oasp4j#568] opened 2017-05-05 07:02 UTC
I have tried to run oasp4j bootified war and also mvn spring-boot:run on server module of oasp4j. Login page will appear but if we will try to login with cook id it will give "Whitable Error Page". I am getting this issue if I will try to login with url  http://localhost:8080/oasp4j-sample-server for cook id. Login for waiter id will work fine.
If I will use  http://localhost:8080/login url and try to login with cook it works fine.
Also if we launch oasp4j with SpringBootApp class cook login works fine.

**Comment by kiran-vadla** [comment] 2017-05-24 13:10
Did a little analysis on the root cause of this issue and found that the context root published in the case of the bootified war is '/' since oasp4j\samples\core\src\main\resources\config\application.properties is excluded from the oasp4j-sample-server.war file . This is as such not an issue since it was decided that ...\config\application.properties will not be part of the war file . In real projects , they could have this file in a shared directory or somewhere  else .  

Hence , in the case of bootified war , the sample application has to be accessed via url 'http://localhost:8080/login'.  If one really needs the context root , they can define it in ..\src\main\resources\application.properties and build the samples project and launch the bootified war . 

I have added these instructions pertaining to 'Running Bootified War' in the wiki https://github.com/devonfw/devon-guide/wiki/getting-started-deployment-on-tomcat#running-bootified-war

@amarinso , As discussed , added the instructions in wiki. Hope we can close this issue ? 

Thanks,
@kiran-vadla

**Comment by kiran-vadla** [comment] 2017-06-02 11:35
This is not a bug . Instructions to access the sample restaurant application in the case of bootified war are documented at https://github.com/devonfw/devon-guide/wiki/getting-started-deployment-on-tomcat#running-bootified-war. Hence closing the issue.

**Closed by kiran-vadla** 2017-06-02 11:35 UTC
Labels: bug
