### ISSUE TITLE
Cannot cancel reservation or free the table if cancelled orders available

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#146] opened 2014-12-16 08:41 UTC
I have reserverd or occupied one table, next perfomed some orders. The table cannot be made free or the reservation cannot be cancelled. Probably correct.

If I remove the orders, they appear as cancelled, but I can't cancel the reservation/free the table too. Is it correct?

**Comment by hohwille** [comment] 2015-06-02 08:44
Duplicate of https://github.com/oasp/oasp4js/issues/33

**Closed by hohwille** 2015-06-02 08:44 UTC
