### ISSUE TITLE
Construct a complex test scenario/broker topology for JMS poc

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4j#65] opened 2014-09-25 21:00 UTC
@maihacke has mentioned in #5 a problem they had in production using ActiveMQ. We should construct similar test case which we could use to check whether the problem still occurs.

**Comment by hohwille** [comment] 2018-09-20 06:49
Duplicate of #63. Still you are more than welcome to contribute to this topic.

**Closed by hohwille** 2018-09-20 06:49 UTC
Labels: messaging, task, test
