### ISSUE TITLE
Add Oder Position is possible without Order ID

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4j#339] opened 2015-11-04 08:12 UTC
The OrderPosition -> Order relation should be not nullable declared in validation constraints and the database.

**Comment by hohwille** [comment] 2015-12-03 16:04
@may-bee did you actually report a bug here? Or did you observe the code and do some guessing?
If there is a bug, please explain more or provide a JUnit to reproduce. If this is not a bug we should close.

**Comment by may-bee** [comment] 2015-12-03 21:59
This bug has been observed from the students implementing the mobile app, which leads to some confusion and inconsistent data during development.

**Comment by hohwille** [comment] 2016-02-19 18:13
We have added a constraint for this. Can someone confirm if this is fixed and close the issue?

**Closed** 2016-03-01 11:01 UTC
