### ISSUE TITLE
logger exception on startup

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4j#154] opened 2015-01-12 12:21 UTC
The sample application currently causes this exception:

```
 13:19:21,098 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@11:82 - RuntimeException in Action for tag [property] java.lang.StringIndexOutOfBoundsException: String index out of range: 44
	at java.lang.StringIndexOutOfBoundsException: String index out of range: 44
	at 	at java.lang.String.charAt(String.java:658)
	at 	at ch.qos.logback.core.pattern.util.RegularEscapeUtil.basicEscape(RegularEscapeUtil.java:69)
	at 	at ch.qos.logback.core.joran.action.PropertyAction.begin(PropertyAction.java:94)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
	at 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
	at 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:282)
	at 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4994)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5492)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hohwille** [comment] 2015-01-12 12:21
Is this a misconfiguration in our logback.xml?

**Comment by hohwille** [comment] 2015-01-12 12:23
Happens when our pattern gets parsed:

> [D: %d{ISO8601}] [P: %-5p] [C: %X{correlationId}] [T: %t] [L: %c] - [M: %m]  %n

**Comment by hohwille** [comment] 2015-01-12 12:27
Nope, its actually this value:

> C:\\Users\\hohwille\\AppData\\Local\\Temp\\\

**Comment by hohwille** [comment] 2015-01-12 12:29
This is a bug/feature of logback (see second "s.charAt(i++);"):

>   public static String basicEscape(String s) {
    char c;
    int len = s.length();
    StringBuilder sbuf = new StringBuilder(len);

    int i = 0;
    while (i < len) {
      c = s.charAt(i++);
      if (c == '\\') {
        c = s.charAt(i++);
        if (c == 'n') {
        ...
        }
      }
      sbuf.append(c);
    }
    return sbuf.toString();
  }

**Comment by hohwille** [comment] 2015-01-12 12:38
The value comes from a variable that gets resolved (by maven) from this source:

>   &lt;property name="filePath" value="${java.io.tmpdir}${file.separator}">&lt;/property>

I removed the last file.separator variable expression to prevent that the string ends with an extra backslash (3 Backslashes) but currently the error still persists.

**Comment by hohwille** [comment] 2015-02-16 08:47
See #177

**Comment by sobkowiak** [comment] 2015-02-16 18:14
Does this error occur only on Windows when `${file.separator}`is appended at the end of `filePath`?

**Comment by sobkowiak** [comment] 2015-02-16 18:30
This problem is caused pyrtly by inconsistent handling of  `java.io.tmpdir` under operating systems (some explanation here https://rationalpi.wordpress.com/2007/01/26/javaiotmpdir-inconsitency/). It was reported as a bug but the bug was rejected (http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4391434)

**Comment by hohwille** [comment] 2015-02-17 10:24
The thing is that we have an odd number of backslashes. The actual bug is IMHO that logback can not handle this (see buggy code above).

**Comment by sobkowiak** [comment] 2015-02-20 07:47
The `java.io.tmpdir` parameter is resolved under Windows as `C:\\Users\\<user>\\AppData\\Local\\Temp\\`. `file.separator` adds the 3rd `\` and logback has problems with this. I haven't found any open issues in Logback. The code remains unchanged as well. It looks like the problem is unknown in Logback community.

I have found a workaround which works on both platforms -  we can attach double `file.separator` at the end of `filePath`

```xml
<property name="filePath" value="${java.io.tmpdir}${file.separator}${file.separator}"></property>
```

I'm gonna to commit this workaround until we find another solution

**Comment by hohwille** [comment] 2015-02-20 07:49
perfect workaround. KISS :)

**Comment by may-bee** [comment] 2015-03-12 20:14
@sobkowiak have you opened an issue in the logback community? If this is really an unknown issue, we should provide some problem description.

I think then we can close this issue.

**Closed by may-bee** 2015-03-12 20:14 UTC
Labels: common, sample
